(("Friday 14"
  ("14:00" "Registrations open & matchmaking")
  ("14:30" "Talk: Introduction to Processing: 2D and 3D graphics with java")
  ("15:30" "Talk: Introduction to LÖVE: rapid 2D graphics with lua")
  ("17:00" "Theme announcement & starting shot")
  ("17:05" "Talk: Introduction to git for version control")
  ("18:00" "Talk: Introduction to Unity")
  ("19:00" "Talk: Introduction to libGDX: make 2D games with java")
  ("22:30" "Time to go home"))
 ("Saturday 15"
  ("10:00" "Doors open")
  ("11:15" "Talk: Introduction to game physics")
  ("15:30" "Talk: A quick guide to pixelart: gotchas and techniques to rapidly improve you art")
  ("17:00" "Talk: Introduction to 2D animation: making a walkcycle")
  ("18:00" "Talk: Making game-music with free tools")
  ("19:00" "Talk: Post-processing effects with fragment-shaders")
  ("24:00" "Time to go home"))
 ("Sunday 16"
  ("10:00" "Doors open")
  ("17:00" "Submission deadline")
  ("17:15" "Showoff on the big screen")
  ("Afterwards" "Prizes & pizza")))
